### ISSUE TITLE
Change to Buffered Output

### ISSUE THREAD

**Issue by y-ken** [fluent-plugins-nursery/fluent-plugin-hipchat#17]
Hi. Some case cause blocking the event loop. Could you please change to buffered output?
Please consider the default value of buffer_flush interval. It might be better to emit in short time.

cf. http://chopl.in/post/2014/01/19/user_bufferedoutput_for_blocking_plugin_instead_of_output/

**Comment by y-ken** [comment]
Hi @okkez 
Would you please check this issue?

**Comment by okkez** [comment]
Sorry, I missed the issue.

This plugin has been already buffered plugin. This plugin runs as buffered by default.
We can implements buffered and non-buffered plugin in one file using v0.14 API.

**Comment by y-ken** [comment]
I did'n know the changes. How to distinguish between non-buffered or buffered?
Do you mean all output plugins works as buffered output since fluentd v0.14?

```
module Fluent::Plugin
  class HipchatOutput < Output
```

**Comment by okkez** [comment]
No. We must implement `write` method to use buffered plugin.

See also http://www.clear-code.com/blog/2016/10/20.html

**Comment by cosmo0920** [comment]
Now, we already migrated to buffered Fluentd v1 output plugin.
